name: "Build"

on:
  push:
    branches:
      - main

jobs:
  # TODO: add support for more OS
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Rust
        run: cargo install cross

      - name: Install Dependencies for macOS
        run: sudo apt-get install -y clang

#      - name: Install Dependencies for Windows
#        run: sudo apt-get install -y mingw-w64

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build