name: "Build"
permissions: {}

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_call:

env:
  RUST_VERSION: 1.84.1

jobs:
  build-native-linux:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:20.04
      options: --user root

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install compilation dependencies
        run: |
          apt-get update
          apt-get install -y \
            curl \
            build-essential \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu

      - name: Setup Rust for x86_64
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-unknown-linux-gnu
          cache: true
          cache-key: x86
          cache-workspaces: "./native -> target"

      - name: Setup Rust for aarch64
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: aarch64-unknown-linux-gnu
          cache: true
          cache-key: aarch64
          cache-workspaces: "./native -> target"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew compileNative-aarch64-unknown-linux-gnu compileNative-x86_64-unknown-linux-gnu
        env:
          NATIVE_BUILD_MODE: "all"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-native-artifacts
          path: oniguruma-jni/build/target

  build-native-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Rust for x86_64
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-pc-windows-msvc
          cache: true
          cache-key: x86
          cache-workspaces: "./native -> target"

      - name: Setup Rust for aarch64
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: aarch64-pc-windows-msvc
          cache: true
          cache-key: aarch64
          cache-workspaces: "./native -> target"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        env:
          NATIVE_BUILD_MODE: "all"
        run: ./gradlew compileNative-x86_64-pc-windows-msvc compileNative-aarch64-pc-windows-msvc

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-native-artifacts
          path: oniguruma-jni/build/target

  build-native-mac:
    runs-on: macos-14

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Rust for x86_64
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-apple-darwin
          cache: true
          cache-key: x86
          cache-workspaces: "./native -> target"

      - name: Setup Rust for aarch64
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: aarch64-apple-darwin
          cache: true
          cache-key: aarch64
          cache-workspaces: "./native -> target"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew compileNative-x86_64-apple-darwin compileNative-aarch64-apple-darwin
        env:
          NATIVE_BUILD_MODE: "all"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-native-artifacts
          path: oniguruma-jni/build/target

  build:
    runs-on: ubuntu-22.04
    needs: [build-native-linux, build-native-windows, build-native-mac]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: oniguruma-jni/build/target
          merge-multiple: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build
        env:
          NATIVE_BUILD_MODE: "skip"