name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version"
        required: true

run-name: "Release ${{ inputs.version }}"

jobs:
  build-native:
    uses: ./.github/workflows/build.yaml

  release:
    runs-on: ubuntu-22.04
    needs: build-native
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: oniguruma-jni/build/target
          merge-multiple: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Release
        uses: joffrey-bion/gradle-library-release-action@v2
        with:
          version: ${{ inputs.version }}
          gpg-signing-key: ${{ secrets.GPG_SECRET_ASCII_ARMORED }}
          gpg-signing-password: ${{ secrets.GPG_PASSWORD }}
          sonatype-username: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          sonatype-password: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
          gradle-publish-tasks: publishAndReleaseToMavenCentral